name: Python CD

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main

jobs:
  test:  # Job for running tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./starter/backend
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: './starter/backend/Pipfile.lock'
    # You can test your matrix by printing the current Python version
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install pipenv
      run: sudo pip install pipenv
    - name: Install dependencies
      run: pipenv install
    - name: Run the tests
      run: pipenv run test

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./starter/backend
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image with environment variable
      run: docker build -t <your_image_name> --build-arg REACT_APP_MOVIE_API_URL=<api_url> .

  # ecr-login:  # Login to ECR with Github Secrets for credentials
  #   runs-on: ubuntu-latest
  #   needs: build  # Wait for build job to complete
  #   steps:
  #     - name: Login to Amazon ECR
  #       uses: aws-actions/amazon-ecr-login@v2
  #       with:
  #         region: <aws_region>  # Replace with your AWS region
  #         secret: ECR_LOGIN  # Reference a secret containing credentials
